import type { Recipe, Category, User, CommunityPost } from "./types"

export const mockUsers: User[] = [
  {
    id: 1,
    email: "chef@hapibara.com",
    username: "chef_hapibara",
    fullName: "Chef Hapibara",
    bio: "Professional chef with 10+ years of experience",
    profileImage: "/diverse-chef-preparing-food.png",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    email: "foodie@hapibara.com",
    username: "foodie_lover",
    fullName: "Maria Garcia",
    bio: "Food enthusiast and recipe creator",
    profileImage: "/woman-cooking.png",
    createdAt: new Date("2024-02-15"),
  },
]

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Breakfast",
    slug: "breakfast",
    description: "Start your day right",
    image: "/hearty-breakfast.png",
  },
  { id: 2, name: "Lunch", slug: "lunch", description: "Midday meals", image: "/diverse-lunch-spread.png" },
  { id: 3, name: "Dinner", slug: "dinner", description: "Evening delights", image: "/cozy-dinner-setting.png" },
  { id: 4, name: "Snacks", slug: "snacks", description: "Quick bites", image: "/assorted-desserts.png" },
  {
    id: 5,
    name: "Sippables",
    slug: "sippables",
    description: "Drinks & beverages",
    image: "/vegetarian-meal.png",
  },
]

const generateRecipes = (): Recipe[] => {
  const recipes: Recipe[] = []
  let recipeId = 1

  // BREAKFAST RECIPES (60+)
  const breakfastRecipes = [
    { title: "Avocado Toast Supreme", slug: "avocado-toast-supreme", prepTime: 10, cookTime: 5 },
    { title: "Fluffy Pancakes with Berries", slug: "fluffy-pancakes-with-berries", prepTime: 15, cookTime: 20 },
    { title: "Veggie Omelette", slug: "veggie-omelette", prepTime: 10, cookTime: 10 },
    { title: "Quinoa Breakfast Bowl", slug: "quinoa-breakfast-bowl", prepTime: 15, cookTime: 20 },
    { title: "Ragi Dosa with Chutney", slug: "ragi-dosa-with-chutney", prepTime: 20, cookTime: 15 },
    { title: "Whole Wheat Toast", slug: "whole-wheat-toast", prepTime: 5, cookTime: 3 },
    { title: "Smoothie Bowl", slug: "smoothie-bowl", prepTime: 10, cookTime: 0 },
    { title: "Idli with Sambar", slug: "idli-with-sambar", prepTime: 30, cookTime: 20 },
    { title: "Chia Seed Pudding", slug: "chia-seed-pudding", prepTime: 10, cookTime: 0 },
    { title: "Poha with Peanuts", slug: "poha-with-peanuts", prepTime: 5, cookTime: 10 },
    { title: "Cornmeal Porridge", slug: "cornmeal-porridge", prepTime: 5, cookTime: 15 },
    { title: "Oat Milk Latte", slug: "oat-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Millet Upma", slug: "millet-upma", prepTime: 10, cookTime: 15 },
    { title: "Vegan Pancakes", slug: "vegan-pancakes", prepTime: 15, cookTime: 20 },
    { title: "Rice Breakfast Congee", slug: "rice-breakfast-congee", prepTime: 10, cookTime: 30 },
    { title: "Sunflower Seed Granola", slug: "sunflower-seed-granola", prepTime: 10, cookTime: 20 },
    { title: "Banana Bread", slug: "banana-bread", prepTime: 15, cookTime: 50 },
    { title: "Almond Butter Toast", slug: "almond-butter-toast", prepTime: 5, cookTime: 3 },
    { title: "Spinach Breakfast Scramble", slug: "spinach-breakfast-scramble", prepTime: 10, cookTime: 8 },
    { title: "Coconut Milk Oatmeal", slug: "coconut-milk-oatmeal", prepTime: 5, cookTime: 10 },
    { title: "Jowar Roti Wrap", slug: "jowar-roti-wrap", prepTime: 15, cookTime: 15 },
    { title: "Pumpkin Seed Parfait", slug: "pumpkin-seed-parfait", prepTime: 10, cookTime: 0 },
    { title: "Brown Rice Porridge", slug: "brown-rice-porridge", prepTime: 10, cookTime: 25 },
    { title: "Hemp Seed Energy Bars", slug: "hemp-seed-energy-bars", prepTime: 15, cookTime: 20 },
    { title: "Matcha Green Tea Toast", slug: "matcha-green-tea-toast", prepTime: 10, cookTime: 5 },
    { title: "Cashew Cream Waffles", slug: "cashew-cream-waffles", prepTime: 20, cookTime: 25 },
    { title: "Bajra Pancakes", slug: "bajra-pancakes", prepTime: 15, cookTime: 20 },
    { title: "Sesame Seed Breakfast Bars", slug: "sesame-seed-breakfast-bars", prepTime: 15, cookTime: 25 },
    { title: "Vegan Scrambled Tofu", slug: "vegan-scrambled-tofu", prepTime: 10, cookTime: 10 },
    { title: "Wild Rice Breakfast", slug: "wild-rice-breakfast", prepTime: 15, cookTime: 20 },
    { title: "Mango Coconut Smoothie", slug: "mango-coconut-smoothie", prepTime: 5, cookTime: 0 },
    { title: "Flax Seed Pancakes", slug: "flax-seed-pancakes", prepTime: 15, cookTime: 20 },
    { title: "Tempeh Bacon Scramble", slug: "tempeh-bacon-scramble", prepTime: 15, cookTime: 15 },
    { title: "Barley Breakfast Porridge", slug: "barley-breakfast-porridge", prepTime: 10, cookTime: 30 },
    { title: "Strawberry Almond Smoothie", slug: "strawberry-almond-smoothie", prepTime: 5, cookTime: 0 },
    { title: "Fonio Breakfast Bowl", slug: "fonio-breakfast-bowl", prepTime: 15, cookTime: 20 },
    { title: "Chickpea Flour Pancakes", slug: "chickpea-flour-pancakes", prepTime: 15, cookTime: 20 },
    { title: "Date Syrup Toast", slug: "date-syrup-toast", prepTime: 5, cookTime: 3 },
    { title: "Soy Milk Cereal", slug: "soy-milk-cereal", prepTime: 5, cookTime: 0 },
    { title: "Moong Dal Porridge", slug: "moong-dal-porridge", prepTime: 10, cookTime: 20 },
    { title: "Peanut Butter Granola", slug: "peanut-butter-granola", prepTime: 10, cookTime: 25 },
    { title: "Rice Milk Pudding", slug: "rice-milk-pudding", prepTime: 10, cookTime: 15 },
    { title: "Black Rice Bowl", slug: "black-rice-bowl", prepTime: 15, cookTime: 25 },
    { title: "Pistachio Protein Smoothie", slug: "pistachio-protein-smoothie", prepTime: 5, cookTime: 0 },
    { title: "Rye Bread Toast", slug: "rye-bread-toast", prepTime: 5, cookTime: 3 },
    { title: "Macadamia Nut Butter Smoothie", slug: "macadamia-nut-butter-smoothie", prepTime: 5, cookTime: 0 },
    { title: "Teff Breakfast Cake", slug: "teff-breakfast-cake", prepTime: 15, cookTime: 30 },
    { title: "Turmeric Oat Milk Latte", slug: "turmeric-oat-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Hazelnut Milk Cereal", slug: "hazelnut-milk-cereal", prepTime: 5, cookTime: 0 },
    { title: "Cottage Cheese Pancakes", slug: "cottage-cheese-pancakes", prepTime: 15, cookTime: 20 },
    { title: "Pecan Pie Oatmeal", slug: "pecan-pie-oatmeal", prepTime: 5, cookTime: 10 },
    { title: "Vegan Sausage Breakfast", slug: "vegan-sausage-breakfast", prepTime: 10, cookTime: 15 },
    { title: "Seaweed Breakfast Rice", slug: "seaweed-breakfast-rice", prepTime: 10, cookTime: 20 },
    { title: "Poppy Seed Muffins", slug: "poppy-seed-muffins", prepTime: 15, cookTime: 25 },
    { title: "Cashew Milk Latte", slug: "cashew-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Kale Green Smoothie", slug: "kale-green-smoothie", prepTime: 5, cookTime: 0 },
    { title: "Tahini Breakfast Spread", slug: "tahini-breakfast-spread", prepTime: 5, cookTime: 0 },
  ]

  // LUNCH RECIPES (60+)
  const lunchRecipes = [
    { title: "Caesar Salad", slug: "caesar-salad", prepTime: 15, cookTime: 10 },
    { title: "Quinoa Buddha Bowl", slug: "quinoa-buddha-bowl", prepTime: 20, cookTime: 30 },
    { title: "Thai Green Curry with Rice", slug: "thai-green-curry-with-rice", prepTime: 15, cookTime: 25 },
    { title: "Lentil Soup", slug: "lentil-soup", prepTime: 15, cookTime: 35 },
    { title: "Chickpea Curry", slug: "chickpea-curry", prepTime: 15, cookTime: 30 },
    { title: "Black Bean Burrito Bowl", slug: "black-bean-burrito-bowl", prepTime: 15, cookTime: 20 },
    { title: "Basmati Rice Pilaf", slug: "basmati-rice-pilaf", prepTime: 10, cookTime: 25 },
    { title: "Vegan Pad Thai", slug: "vegan-pad-thai", prepTime: 20, cookTime: 15 },
    { title: "Falafel Wrap", slug: "falafel-wrap", prepTime: 20, cookTime: 15 },
    { title: "Soba Noodle Salad", slug: "soba-noodle-salad", prepTime: 15, cookTime: 10 },
    { title: "White Rice with Dal", slug: "white-rice-with-dal", prepTime: 15, cookTime: 25 },
    { title: "Vegetable Stir Fry", slug: "vegetable-stir-fry", prepTime: 15, cookTime: 15 },
    { title: "Tempeh Buddha Bowl", slug: "tempeh-buddha-bowl", prepTime: 20, cookTime: 20 },
    { title: "Tofu Curry", slug: "tofu-curry", prepTime: 15, cookTime: 25 },
    { title: "Brown Rice Salad", slug: "brown-rice-salad", prepTime: 20, cookTime: 15 },
    { title: "Red Rice Bowl", slug: "red-rice-bowl", prepTime: 15, cookTime: 25 },
    { title: "Ramen Noodle Soup", slug: "ramen-noodle-soup", prepTime: 15, cookTime: 20 },
    { title: "Moong Dal Khichdi", slug: "moong-dal-khichdi", prepTime: 15, cookTime: 25 },
    { title: "Rajma Masala", slug: "rajma-masala", prepTime: 20, cookTime: 35 },
    { title: "Chana Masala", slug: "chana-masala", prepTime: 15, cookTime: 30 },
    { title: "Jackfruit Biryani", slug: "jackfruit-biryani", prepTime: 25, cookTime: 35 },
    { title: "Mushroom Risotto", slug: "mushroom-risotto", prepTime: 20, cookTime: 30 },
    { title: "Jowar Roti with Curry", slug: "jowar-roti-with-curry", prepTime: 15, cookTime: 20 },
    { title: "Bajra Khichdi", slug: "bajra-khichdi", prepTime: 15, cookTime: 25 },
    { title: "Ragi Lunch Bowl", slug: "ragi-lunch-bowl", prepTime: 15, cookTime: 20 },
    { title: "Fonio Salad", slug: "fonio-salad", prepTime: 15, cookTime: 10 },
    { title: "Glass Noodle Stir Fry", slug: "glass-noodle-stir-fry", prepTime: 15, cookTime: 15 },
    { title: "Rice Noodle Soup", slug: "rice-noodle-soup", prepTime: 15, cookTime: 20 },
    { title: "Sunflower Seed Salad", slug: "sunflower-seed-salad", prepTime: 15, cookTime: 0 },
    { title: "Pumpkin Seed Grain Bowl", slug: "pumpkin-seed-grain-bowl", prepTime: 20, cookTime: 25 },
    { title: "Sesame Noodle Bowl", slug: "sesame-noodle-bowl", prepTime: 15, cookTime: 15 },
    { title: "Hemp Seed Salad", slug: "hemp-seed-salad", prepTime: 15, cookTime: 0 },
    { title: "Poppy Seed Pasta", slug: "poppy-seed-pasta", prepTime: 15, cookTime: 15 },
    { title: "Mustard Seed Vegetable", slug: "mustard-seed-vegetable", prepTime: 15, cookTime: 15 },
    { title: "Nigella Seed Naan", slug: "nigella-seed-naan", prepTime: 20, cookTime: 10 },
    { title: "Fenugreek Leaf Curry", slug: "fenugreek-leaf-curry", prepTime: 15, cookTime: 20 },
    { title: "Cumin Rice", slug: "cumin-rice", prepTime: 10, cookTime: 20 },
    { title: "Coriander Leaf Salad", slug: "coriander-leaf-salad", prepTime: 15, cookTime: 0 },
    { title: "Fennel Infused Dal", slug: "fennel-infused-dal", prepTime: 15, cookTime: 25 },
    { title: "Cardamom Rice Pilaf", slug: "cardamom-rice-pilaf", prepTime: 15, cookTime: 25 },
    { title: "Clove Spiced Lentils", slug: "clove-spiced-lentils", prepTime: 15, cookTime: 30 },
    { title: "Cinnamon Rice", slug: "cinnamon-rice", prepTime: 10, cookTime: 20 },
    { title: "Nutmeg Dal", slug: "nutmeg-dal", prepTime: 15, cookTime: 25 },
    { title: "Turmeric Rice Bowl", slug: "turmeric-rice-bowl", prepTime: 15, cookTime: 25 },
    { title: "Red Chilli Curry", slug: "red-chilli-curry", prepTime: 15, cookTime: 25 },
    { title: "Garam Masala Chickpeas", slug: "garam-masala-chickpeas", prepTime: 15, cookTime: 25 },
    { title: "Sambar Rice", slug: "sambar-rice", prepTime: 20, cookTime: 25 },
    { title: "Chaat Masala Popcorn Rice", slug: "chaat-masala-popcorn-rice", prepTime: 15, cookTime: 20 },
    { title: "Kala Namak Salad", slug: "kala-namak-salad", prepTime: 15, cookTime: 0 },
    { title: "Asafoetida Dal", slug: "asafoetida-dal", prepTime: 15, cookTime: 25 },
    { title: "Aamchur Mango Rice", slug: "aamchur-mango-rice", prepTime: 15, cookTime: 20 },
    { title: "Kasuri Methi Noodles", slug: "kasuri-methi-noodles", prepTime: 15, cookTime: 15 },
    { title: "Oregano Roasted Vegetables", slug: "oregano-roasted-vegetables", prepTime: 20, cookTime: 30 },
    { title: "Couscous Salad", slug: "couscous-salad", prepTime: 20, cookTime: 15 },
  ]

  // DINNER RECIPES (60+)
  const dinnerRecipes = [
    { title: "Chocolate Lava Cake", slug: "chocolate-lava-cake", prepTime: 15, cookTime: 12 },
    { title: "Vegan Buddha Bowl", slug: "vegan-buddha-bowl", prepTime: 20, cookTime: 30 },
    { title: "Classic Margherita Pizza", slug: "classic-margherita-pizza", prepTime: 20, cookTime: 15 },
    { title: "Pasta Primavera", slug: "pasta-primavera", prepTime: 15, cookTime: 20 },
    { title: "Vegetable Lasagna", slug: "vegetable-lasagna", prepTime: 30, cookTime: 45 },
    { title: "Mushroom Stroganoff", slug: "mushroom-stroganoff", prepTime: 20, cookTime: 25 },
    { title: "Vegan Tacos", slug: "vegan-tacos", prepTime: 20, cookTime: 15 },
    { title: "Spinach Stuffed Bell Peppers", slug: "spinach-stuffed-bell-peppers", prepTime: 20, cookTime: 35 },
    { title: "Vegetable Fried Rice", slug: "vegetable-fried-rice", prepTime: 15, cookTime: 15 },
    { title: "Lentil Bolognese", slug: "lentil-bolognese", prepTime: 15, cookTime: 30 },
    { title: "Thai Basil Noodles", slug: "thai-basil-noodles", prepTime: 15, cookTime: 15 },
    { title: "Eggplant Parmesan", slug: "eggplant-parmesan", prepTime: 20, cookTime: 35 },
    { title: "Chickpea Tikka Masala", slug: "chickpea-tikka-masala", prepTime: 20, cookTime: 30 },
    { title: "Black Bean Tacos", slug: "black-bean-tacos", prepTime: 15, cookTime: 15 },
    { title: "Vegetable Biryani", slug: "vegetable-biryani", prepTime: 25, cookTime: 40 },
    { title: "Paneer Tikka Masala", slug: "paneer-tikka-masala", prepTime: 20, cookTime: 30 },
    { title: "Tofu Steak", slug: "tofu-steak", prepTime: 20, cookTime: 20 },
    { title: "Tempeh Tacos", slug: "tempeh-tacos", prepTime: 15, cookTime: 15 },
    { title: "Jackfruit Pulled Pork", slug: "jackfruit-pulled-pork", prepTime: 20, cookTime: 30 },
    { title: "Seitan Wellington", slug: "seitan-wellington", prepTime: 30, cookTime: 45 },
    { title: "Walnut Mushroom Meatballs", slug: "walnut-mushroom-meatballs", prepTime: 20, cookTime: 25 },
    { title: "Cashew Cream Pasta", slug: "cashew-cream-pasta", prepTime: 15, cookTime: 20 },
    { title: "Almond Butter Noodles", slug: "almond-butter-noodles", prepTime: 15, cookTime: 15 },
    { title: "Peanut Sauce Pasta", slug: "peanut-sauce-pasta", prepTime: 15, cookTime: 20 },
    { title: "Tahini Noodles", slug: "tahini-noodles", prepTime: 15, cookTime: 15 },
    { title: "Sunflower Seed Burger", slug: "sunflower-seed-burger", prepTime: 20, cookTime: 15 },
    { title: "Pumpkin Seed Patties", slug: "pumpkin-seed-patties", prepTime: 20, cookTime: 20 },
    { title: "Sesame Crusted Tofu", slug: "sesame-crusted-tofu", prepTime: 15, cookTime: 20 },
    { title: "Hemp Seed Salad Dinner", slug: "hemp-seed-salad-dinner", prepTime: 20, cookTime: 0 },
    { title: "Poppy Seed Noodles", slug: "poppy-seed-noodles", prepTime: 15, cookTime: 15 },
    { title: "Mustard Seed Tempeh", slug: "mustard-seed-tempeh", prepTime: 15, cookTime: 20 },
    { title: "Nigella Seed Pizza", slug: "nigella-seed-pizza", prepTime: 20, cookTime: 20 },
    { title: "Fenugreek Leaf Tofu", slug: "fenugreek-leaf-tofu", prepTime: 15, cookTime: 15 },
    { title: "Cumin Spiced Lentils", slug: "cumin-spiced-lentils", prepTime: 15, cookTime: 30 },
    { title: "Coriander Chickpea Curry", slug: "coriander-chickpea-curry", prepTime: 15, cookTime: 30 },
    { title: "Fennel Vegetable Stew", slug: "fennel-vegetable-stew", prepTime: 20, cookTime: 35 },
    { title: "Cardamom Rice Dinner", slug: "cardamom-rice-dinner", prepTime: 15, cookTime: 25 },
    { title: "Clove Dal", slug: "clove-dal", prepTime: 15, cookTime: 30 },
    { title: "Cinnamon Chickpea Stew", slug: "cinnamon-chickpea-stew", prepTime: 15, cookTime: 35 },
    { title: "Star Anise Noodles", slug: "star-anise-noodles", prepTime: 15, cookTime: 15 },
    { title: "Nutmeg Vegetable Gratin", slug: "nutmeg-vegetable-gratin", prepTime: 20, cookTime: 35 },
    { title: "Turmeric Cauliflower Steak", slug: "turmeric-cauliflower-steak", prepTime: 15, cookTime: 25 },
    { title: "Red Chilli Tempeh Stir Fry", slug: "red-chilli-tempeh-stir-fry", prepTime: 15, cookTime: 15 },
    { title: "Garam Masala Dal Makhani", slug: "garam-masala-dal-makhani", prepTime: 15, cookTime: 35 },
    { title: "Sambar Vegetables", slug: "sambar-vegetables", prepTime: 20, cookTime: 25 },
    { title: "Chaat Masala Noodles", slug: "chaat-masala-noodles", prepTime: 15, cookTime: 15 },
    { title: "Kala Namak Tofu", slug: "kala-namak-tofu", prepTime: 15, cookTime: 15 },
    { title: "Asafoetida Tempeh", slug: "asafoetida-tempeh", prepTime: 15, cookTime: 15 },
    { title: "Aamchur Chickpeas", slug: "aamchur-chickpeas", prepTime: 15, cookTime: 25 },
    { title: "Kasuri Methi Paneer", slug: "kasuri-methi-paneer", prepTime: 15, cookTime: 20 },
    { title: "Oregano Pasta Dinner", slug: "oregano-pasta-dinner", prepTime: 15, cookTime: 20 },
    { title: "Basil Tomato Pasta", slug: "basil-tomato-pasta", prepTime: 15, cookTime: 20 },
    { title: "Coconut Milk Curry Dinner", slug: "coconut-milk-curry-dinner", prepTime: 15, cookTime: 30 },
  ]

  // SNACKS RECIPES (60+)
  const snacksRecipes = [
    { title: "Hummus with Veggies", slug: "hummus-with-veggies", prepTime: 15, cookTime: 0 },
    { title: "Roasted Chickpeas", slug: "roasted-chickpeas", prepTime: 10, cookTime: 25 },
    { title: "Guacamole and Chips", slug: "guacamole-and-chips", prepTime: 10, cookTime: 0 },
    { title: "Trail Mix", slug: "trail-mix", prepTime: 10, cookTime: 0 },
    { title: "Energy Balls", slug: "energy-balls", prepTime: 15, cookTime: 0 },
    { title: "Vegan Cheese Crackers", slug: "vegan-cheese-crackers", prepTime: 15, cookTime: 15 },
    { title: "Roasted Nuts", slug: "roasted-nuts", prepTime: 10, cookTime: 20 },
    { title: "Fruit and Nut Bar", slug: "fruit-and-nut-bar", prepTime: 15, cookTime: 20 },
    { title: "Vegetable Chips", slug: "vegetable-chips", prepTime: 15, cookTime: 30 },
    { title: "Popcorn with Herbs", slug: "popcorn-with-herbs", prepTime: 5, cookTime: 10 },
    { title: "Seaweed Snacks", slug: "seaweed-snacks", prepTime: 5, cookTime: 5 },
    { title: "Dried Fruit Mix", slug: "dried-fruit-mix", prepTime: 10, cookTime: 0 },
    { title: "Coconut Bites", slug: "coconut-bites", prepTime: 15, cookTime: 15 },
    { title: "Almond Energy Balls", slug: "almond-energy-balls", prepTime: 15, cookTime: 0 },
    { title: "Peanut Butter Cookies", slug: "peanut-butter-cookies", prepTime: 15, cookTime: 12 },
    { title: "Cashew Cheese Dip", slug: "cashew-cheese-dip", prepTime: 10, cookTime: 0 },
    { title: "Sunflower Seed Butter Crackers", slug: "sunflower-seed-butter-crackers", prepTime: 15, cookTime: 15 },
    { title: "Pumpkin Seeds Roasted", slug: "pumpkin-seeds-roasted", prepTime: 10, cookTime: 20 },
    { title: "Sesame Brittle", slug: "sesame-brittle", prepTime: 10, cookTime: 15 },
    { title: "Hemp Seed Bars", slug: "hemp-seed-bars", prepTime: 15, cookTime: 20 },
    { title: "Poppy Seed Crackers", slug: "poppy-seed-crackers", prepTime: 15, cookTime: 15 },
    { title: "Mustard Seed Crisps", slug: "mustard-seed-crisps", prepTime: 10, cookTime: 20 },
    { title: "Nigella Seed Biscuits", slug: "nigella-seed-biscuits", prepTime: 15, cookTime: 15 },
    { title: "Cumin Flavored Popcorn", slug: "cumin-flavored-popcorn", prepTime: 5, cookTime: 10 },
    { title: "Coriander Roasted Nuts", slug: "coriander-roasted-nuts", prepTime: 10, cookTime: 20 },
    { title: "Fennel Seed Candy", slug: "fennel-seed-candy", prepTime: 10, cookTime: 15 },
    { title: "Cardamom Cookies", slug: "cardamom-cookies", prepTime: 15, cookTime: 15 },
    { title: "Clove Spiced Nuts", slug: "clove-spiced-nuts", prepTime: 10, cookTime: 20 },
    { title: "Cinnamon Sugar Chips", slug: "cinnamon-sugar-chips", prepTime: 15, cookTime: 25 },
    { title: "Star Anise Popcorn", slug: "star-anise-popcorn", prepTime: 5, cookTime: 10 },
    { title: "Nutmeg Roasted Seeds", slug: "nutmeg-roasted-seeds", prepTime: 10, cookTime: 20 },
    { title: "Turmeric Roasted Chickpeas", slug: "turmeric-roasted-chickpeas", prepTime: 10, cookTime: 25 },
    { title: "Red Chilli Roasted Almonds", slug: "red-chilli-roasted-almonds", prepTime: 10, cookTime: 20 },
    { title: "Garam Masala Trail Mix", slug: "garam-masala-trail-mix", prepTime: 10, cookTime: 0 },
    { title: "Sambar Powder Crackers", slug: "sambar-powder-crackers", prepTime: 15, cookTime: 15 },
    { title: "Chaat Masala Popcorn", slug: "chaat-masala-popcorn", prepTime: 5, cookTime: 10 },
    { title: "Kala Namak Roasted Nuts", slug: "kala-namak-roasted-nuts", prepTime: 10, cookTime: 20 },
    { title: "Asafoetida Crackers", slug: "asafoetida-crackers", prepTime: 15, cookTime: 15 },
    { title: "Aamchur Chips", slug: "aamchur-chips", prepTime: 10, cookTime: 20 },
    { title: "Kasuri Methi Popcorn", slug: "kasuri-methi-popcorn", prepTime: 5, cookTime: 10 },
    { title: "Oregano Flavored Nuts", slug: "oregano-flavored-nuts", prepTime: 10, cookTime: 20 },
    { title: "Basil Crackers", slug: "basil-crackers", prepTime: 15, cookTime: 15 },
    { title: "Vegan Protein Bars", slug: "vegan-protein-bars", prepTime: 15, cookTime: 20 },
    { title: "Date Energy Bites", slug: "date-energy-bites", prepTime: 15, cookTime: 0 },
    { title: "Granola Clusters", slug: "granola-clusters", prepTime: 15, cookTime: 25 },
    { title: "Chia Pudding Cups", slug: "chia-pudding-cups", prepTime: 15, cookTime: 0 },
    { title: "Coconut Yogurt Parfait", slug: "coconut-yogurt-parfait", prepTime: 10, cookTime: 0 },
    { title: "Beetroot Chips", slug: "beetroot-chips", prepTime: 15, cookTime: 30 },
    { title: "Kale Chips", slug: "kale-chips", prepTime: 10, cookTime: 20 },
    { title: "Tempeh Bacon Bits", slug: "tempeh-bacon-bits", prepTime: 15, cookTime: 20 },
    { title: "Tofu Jerky", slug: "tofu-jerky", prepTime: 15, cookTime: 45 },
    { title: "Soy Chips", slug: "soy-chips", prepTime: 10, cookTime: 25 },
  ]

  // SIPPABLES RECIPES (60+)
  const sippablesRecipes = [
    { title: "Matcha Latte", slug: "matcha-latte", prepTime: 5, cookTime: 5 },
    { title: "Almond Milk Smoothie", slug: "almond-milk-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Green Juice", slug: "green-juice", prepTime: 15, cookTime: 0 },
    { title: "Protein Shake", slug: "protein-shake", prepTime: 5, cookTime: 0 },
    { title: "Kombucha Tea", slug: "kombucha-tea", prepTime: 5, cookTime: 5 },
    { title: "Herbal Tea", slug: "herbal-tea", prepTime: 5, cookTime: 5 },
    { title: "Iced Coffee", slug: "iced-coffee", prepTime: 5, cookTime: 5 },
    { title: "Oat Milk Latte", slug: "oat-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Coconut Water Smoothie", slug: "coconut-water-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Turmeric Golden Milk", slug: "turmeric-golden-milk", prepTime: 5, cookTime: 5 },
    { title: "Ginger Lemon Tea", slug: "ginger-lemon-tea", prepTime: 5, cookTime: 5 },
    { title: "Chamomile Tea", slug: "chamomile-tea", prepTime: 5, cookTime: 5 },
    { title: "Peppermint Tea", slug: "peppermint-tea", prepTime: 5, cookTime: 5 },
    { title: "Apple Cider Vinegar Drink", slug: "apple-cider-vinegar-drink", prepTime: 5, cookTime: 0 },
    { title: "Spirulina Smoothie", slug: "spirulina-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Cacao Hot Chocolate", slug: "cacao-hot-chocolate", prepTime: 5, cookTime: 5 },
    { title: "Maca Root Smoothie", slug: "maca-root-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Ashwagandha Milk", slug: "ashwagandha-milk", prepTime: 5, cookTime: 5 },
    { title: "Beetroot Juice", slug: "beetroot-juice", prepTime: 10, cookTime: 0 },
    { title: "Carrot Orange Juice", slug: "carrot-orange-juice", prepTime: 10, cookTime: 0 },
    { title: "Soy Milk Latte", slug: "soy-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Rice Milk Smoothie", slug: "rice-milk-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Cashew Milk Latte", slug: "cashew-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Hemp Milk Smoothie", slug: "hemp-milk-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Pea Milk Latte", slug: "pea-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Hazelnut Milk Latte", slug: "hazelnut-milk-latte", prepTime: 5, cookTime: 5 },
    { title: "Blueberry Smoothie", slug: "blueberry-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Strawberry Smoothie", slug: "strawberry-smoothie", prepTime: 10, cookTime: 0 },
    { title: "Mango Lassi", slug: "mango-lassi", prepTime: 10, cookTime: 0 },
    { title: "Banana Date Shake", slug: "banana-date-shake", prepTime: 10, cookTime: 0 },
    { title: "Mint Lemonade", slug: "mint-lemonade", prepTime: 10, cookTime: 0 },
    { title: "Iced Green Tea", slug: "iced-green-tea", prepTime: 10, cookTime: 10 },
    { title: "Hibiscus Tea", slug: "hibiscus-tea", prepTime: 5, cookTime: 5 },
    { title: "Lavender Tea", slug: "lavender-tea", prepTime: 5, cookTime: 5 },
    { title: "Rose Hip Tea", slug: "rose-hip-tea", prepTime: 5, cookTime: 5 },
    { title: "Black Tea with Spices", slug: "black-tea-with-spices", prepTime: 5, cookTime: 5 },
    { title: "Rooibos Tea", slug: "rooibos-tea", prepTime: 5, cookTime: 5 },
    { title: "White Tea", slug: "white-tea", prepTime: 5, cookTime: 5 },
    { title: "Oolong Tea", slug: "oolong-tea", prepTime: 5, cookTime: 5 },
    { title: "Jasmine Tea", slug: "jasmine-tea", prepTime: 5, cookTime: 5 },
    { title: "Cold Brew Coffee", slug: "cold-brew-coffee", prepTime: 15, cookTime: 600 },
    { title: "Espresso Shot", slug: "espresso-shot", prepTime: 2, cookTime: 1 },
    { title: "Americano", slug: "americano", prepTime: 5, cookTime: 5 },
    { title: "Cappuccino", slug: "cappuccino", prepTime: 5, cookTime: 5 },
    { title: "Macchiato", slug: "macchiato", prepTime: 5, cookTime: 5 },
    { title: "Flat White", slug: "flat-white", prepTime: 5, cookTime: 5 },
    { title: "Mocha Latte", slug: "mocha-latte", prepTime: 5, cookTime: 5 },
    { title: "Vanilla Latte", slug: "vanilla-latte", prepTime: 5, cookTime: 5 },
    { title: "Caramel Macchiato", slug: "caramel-macchiato", prepTime: 5, cookTime: 5 },
    { title: "Hazelnut Latte", slug: "hazelnut-latte", prepTime: 5, cookTime: 5 },
    { title: "Coconut Milk Coffee", slug: "coconut-milk-coffee", prepTime: 5, cookTime: 5 },
    { title: "Cardamom Tea", slug: "cardamom-tea", prepTime: 5, cookTime: 5 },
    { title: "Clove Tea", slug: "clove-tea", prepTime: 5, cookTime: 5 },
    { title: "Cinnamon Spiced Tea", slug: "cinnamon-spiced-tea", prepTime: 5, cookTime: 5 },
    { title: "Fennel Tea", slug: "fennel-tea", prepTime: 5, cookTime: 5 },
  ]

  // Combine all recipe arrays
  const allRecipeArrays = [
    breakfastRecipes.map((r) => ({ ...r, category: "breakfast" })),
    lunchRecipes.map((r) => ({ ...r, category: "lunch" })),
    dinnerRecipes.map((r) => ({ ...r, category: "dinner" })),
    snacksRecipes.map((r) => ({ ...r, category: "snacks" })),
    sippablesRecipes.map((r) => ({ ...r, category: "sippables" })),
  ].flat()

  // Create Recipe objects
  for (const recipeData of allRecipeArrays) {
    const categoryObj = mockCategories.find((cat) => cat.slug === recipeData.category)
    recipes.push({
      id: recipeId++,
      userId: recipeId % 2 === 0 ? 1 : 2,
      title: recipeData.title,
      slug: recipeData.slug,
      description: `Delicious ${recipeData.title} recipe`,
      prepTime: recipeData.prepTime,
      cookTime: recipeData.cookTime,
      servings: 2 + (recipeId % 4),
      difficulty: recipeId % 3 === 0 ? "Easy" : recipeId % 3 === 1 ? "Medium" : "Hard",
      image: "/placeholder.svg?height=400&width=400&query=" + encodeURIComponent(recipeData.title),
      createdAt: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000),
      user: mockUsers[recipeId % 2],
      categories: categoryObj ? [categoryObj] : [],
      averageRating: 3.5 + Math.random() * 1.5,
      reviewCount: Math.floor(Math.random() * 200),
      likeCount: Math.floor(Math.random() * 500),
      ingredients: [
        {
          id: recipeId * 10 + 1,
          recipeId: recipeId,
          item: "Main ingredient",
          quantity: "1",
          unit: "cup",
          orderIndex: 1,
        },
        {
          id: recipeId * 10 + 2,
          recipeId: recipeId,
          item: "Secondary ingredient",
          quantity: "2",
          unit: "tbsp",
          orderIndex: 2,
        },
      ],
      instructions: [
        { id: recipeId * 10 + 1, recipeId: recipeId, stepNumber: 1, instruction: "Prepare all ingredients" },
        { id: recipeId * 10 + 2, recipeId: recipeId, stepNumber: 2, instruction: "Combine ingredients" },
        { id: recipeId * 10 + 3, recipeId: recipeId, stepNumber: 3, instruction: "Cook and serve" },
      ],
    })
  }

  return recipes
}

export const mockRecipes = generateRecipes()

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 1,
    userId: 1,
    title: "My Cooking Journey",
    content: "Started cooking professionally 10 years ago and never looked back! Here are some tips for beginners...",
    image: "/cooking-journey.jpg",
    createdAt: new Date("2024-03-01"),
    user: mockUsers[0],
    commentCount: 45,
    likeCount: 234,
  },
  {
    id: 2,
    userId: 2,
    title: "Best Kitchen Tools",
    content: "After years of cooking, these are the tools I cannot live without. Let me know what your favorites are!",
    image: "/assorted-kitchen-tools.png",
    createdAt: new Date("2024-03-10"),
    user: mockUsers[1],
    commentCount: 23,
    likeCount: 156,
  },
]
